do not use widgetSelectedAdapter - it is missing on some installations that use external SWT (e.g. Linux ARM)
GA reports: org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NoSuchMethodError: org.eclipse.swt.events.SelectionListener.widgetSelectedAdapter(Ljava/util/function/Consumer;)Lorg/eclipse/swt/events/SelectionListener;) (46) net.azib.ipscan.gui.GUI.showMainWindow:51